---
title: Providence Today
timezone: America/New_York
collections:
  events:
    title: Events
    output: true
    base: "Starts At"
    permalink: "/:collection/:year/:month/:day/:path"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    icon image: 
- scope:
    path: ''
    type: events
  values:
    Starts At: 
    Ends At: 
    Short Location: 
    Full Address: 
    Description: 
    Image: 
email: pvdtoday@gmail.com
description: Providence Today (pvd.today) is a list of events in and around Providence,
  RI.
baseurl: 
url: http://pvd.today
markdown: kramdown
